---
# This file and plugin.spec are required by Infrared project

- hosts: tester
  tasks:

    - name: Remap infrared parameters to role variables
      set_fact:
        "{{ item.key }}": "{{ item.value }}"
      with_dict: "{{ test }}"

    - name: refstack-client-ansible-role
      include_role:
        name: refstack-client-ansible-role

