---
# This file and plugin.spec are required by Infrared project

- hosts: undercloud
  remote_user: stack
  roles:
    - refstack-client-ansible-role

  pre_tasks:
    - name: Set url_cirros_image
      set_fact:
        url_cirros_image: "{{ test.url_cirros_image }}"
      when: test.url_cirros_image

    - name: Set source_credentials
      set_fact:
        source_credentials: "{{ test.source_credentials }}"
      when: test.source_credentials is defined

    - name: Set refstack_client_source
      set_fact:
        refstack_client_source: "{{ test.refstack_client_source }}"
      when: test.refstack_client_source

    - name: Set tempestconf_source
      set_fact:
        tempestconf_source: "{{ test.tempestconf_source }}"
      when: test.tempestconf_source

    - name: Set tempestconf_venv
      set_fact:
        tempestconf_venv: "{{ test.tempestconf_venv }}"
      when: test.tempestconf_venv

    - name: Set url_cirros_image
      set_fact:
        url_cirros_image: "{{ test.url_cirros_image }}"
      when: test.url_cirros_image

    - name: Set tempest_config_path
      set_fact:
        tempest_config_path: "{{ test.tempest_config_path }}"
      when: test.tempest_config_path

